[2023-09-14T13:43:08.443+0000] {processor.py:156} INFO - Started process (PID=12727) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:08.455+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:43:08.472+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:43:08.471+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:09.937+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:43:09.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:43:10.076+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:10.535+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 2.204 seconds
[2023-09-14T13:43:40.980+0000] {processor.py:156} INFO - Started process (PID=12783) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:40.982+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:43:40.985+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:43:40.984+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:41.101+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:43:41.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:43:41.106+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:43:41.174+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.209 seconds
[2023-09-14T13:44:11.460+0000] {processor.py:156} INFO - Started process (PID=12840) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:11.462+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:44:11.472+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:44:11.472+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:11.521+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:44:11.512+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:44:11.524+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:11.588+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.132 seconds
[2023-09-14T13:44:42.104+0000] {processor.py:156} INFO - Started process (PID=12898) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:42.107+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:44:42.116+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:44:42.115+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:42.157+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:44:42.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:44:42.177+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:44:42.270+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.171 seconds
[2023-09-14T13:45:12.898+0000] {processor.py:156} INFO - Started process (PID=12955) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:12.935+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:45:12.952+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:45:12.951+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:13.428+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:45:13.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:45:13.456+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:13.681+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.901 seconds
[2023-09-14T13:45:44.521+0000] {processor.py:156} INFO - Started process (PID=13011) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:44.523+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:45:44.524+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:45:44.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:44.669+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:45:44.649+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:45:44.672+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:45:44.710+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.193 seconds
[2023-09-14T13:46:15.483+0000] {processor.py:156} INFO - Started process (PID=13068) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:15.485+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:46:15.487+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:46:15.487+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:15.557+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:46:15.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:46:15.565+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:15.631+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.152 seconds
[2023-09-14T13:46:46.068+0000] {processor.py:156} INFO - Started process (PID=13125) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:46.069+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:46:46.071+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:46:46.071+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:46.131+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:46:46.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:46:46.135+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:46:46.170+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.107 seconds
[2023-09-14T13:47:16.569+0000] {processor.py:156} INFO - Started process (PID=13182) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:16.570+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:47:16.571+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:47:16.571+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:16.652+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:47:16.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:47:16.655+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:16.716+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.153 seconds
[2023-09-14T13:47:46.788+0000] {processor.py:156} INFO - Started process (PID=13239) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:46.790+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:47:46.791+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:47:46.791+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:46.834+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:47:46.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:47:46.837+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:47:46.878+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.093 seconds
[2023-09-14T13:48:16.960+0000] {processor.py:156} INFO - Started process (PID=13296) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:16.964+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:48:16.974+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:48:16.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:17.068+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:48:17.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:48:17.071+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:17.112+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.156 seconds
[2023-09-14T13:48:47.597+0000] {processor.py:156} INFO - Started process (PID=13352) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:47.599+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:48:47.600+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:48:47.600+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:47.675+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:48:47.649+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:48:47.678+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:48:47.712+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.127 seconds
[2023-09-14T13:49:18.783+0000] {processor.py:156} INFO - Started process (PID=13409) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:18.799+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:49:18.815+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:49:18.815+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:18.984+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:49:18.950+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:49:19.002+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:19.071+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.292 seconds
[2023-09-14T13:49:49.709+0000] {processor.py:156} INFO - Started process (PID=13461) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:49.710+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:49:49.711+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:49:49.711+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:49.770+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:49:49.755+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:49:49.779+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:49:49.844+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.139 seconds
[2023-09-14T13:50:20.616+0000] {processor.py:156} INFO - Started process (PID=13518) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:20.617+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:50:20.618+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:50:20.618+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:20.682+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:50:20.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:50:20.685+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:20.727+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.120 seconds
[2023-09-14T13:50:50.793+0000] {processor.py:156} INFO - Started process (PID=13575) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:50.796+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:50:50.800+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:50:50.800+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:50.892+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:50:50.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:50:50.896+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:50:50.946+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.155 seconds
[2023-09-14T13:51:21.513+0000] {processor.py:156} INFO - Started process (PID=13632) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:21.514+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:51:21.516+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:51:21.515+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:21.616+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:51:21.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:51:21.629+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:21.677+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.177 seconds
[2023-09-14T13:51:52.161+0000] {processor.py:156} INFO - Started process (PID=13690) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:52.165+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:51:52.178+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:51:52.178+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:52.246+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:51:52.238+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:51:52.249+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:51:52.289+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.132 seconds
[2023-09-14T13:52:22.408+0000] {processor.py:156} INFO - Started process (PID=13748) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:22.409+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:52:22.410+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:52:22.410+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:22.472+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:52:22.464+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:52:22.477+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:22.530+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.135 seconds
[2023-09-14T13:52:53.439+0000] {processor.py:156} INFO - Started process (PID=13805) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:53.440+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:52:53.442+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:52:53.441+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:53.529+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:52:53.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:52:53.533+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:52:53.601+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.165 seconds
[2023-09-14T13:53:26.867+0000] {processor.py:156} INFO - Started process (PID=13867) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:26.868+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:53:26.879+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:53:26.879+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:26.931+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:53:26.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:53:26.935+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:27.013+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.150 seconds
[2023-09-14T13:53:57.089+0000] {processor.py:156} INFO - Started process (PID=13920) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:57.091+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:53:57.092+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:53:57.092+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:57.213+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:53:57.169+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:53:57.217+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:53:57.253+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.167 seconds
[2023-09-14T13:54:30.121+0000] {processor.py:156} INFO - Started process (PID=13971) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:54:30.123+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:54:30.146+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:54:30.146+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:54:30.335+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:54:30.266+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:54:30.339+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:54:30.401+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.284 seconds
[2023-09-14T13:55:01.394+0000] {processor.py:156} INFO - Started process (PID=14027) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:01.402+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:55:01.404+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:55:01.404+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:01.547+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:55:01.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:55:01.562+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:01.605+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.215 seconds
[2023-09-14T13:55:36.744+0000] {processor.py:156} INFO - Started process (PID=14081) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:36.746+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:55:36.748+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:55:36.748+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:36.912+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:55:36.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:55:36.916+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:55:36.971+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.233 seconds
[2023-09-14T13:56:07.746+0000] {processor.py:156} INFO - Started process (PID=14137) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:07.749+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:56:07.750+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:56:07.750+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:07.816+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:56:07.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:56:07.822+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:07.864+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.121 seconds
[2023-09-14T13:56:38.141+0000] {processor.py:156} INFO - Started process (PID=14195) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:38.142+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:56:38.154+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:56:38.154+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:38.351+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:56:38.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:56:38.377+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:56:38.444+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.307 seconds
[2023-09-14T13:57:09.088+0000] {processor.py:156} INFO - Started process (PID=14252) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:09.090+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:57:09.091+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:57:09.091+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:09.136+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:57:09.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:57:09.140+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:09.177+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.092 seconds
[2023-09-14T13:57:39.383+0000] {processor.py:156} INFO - Started process (PID=14309) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:39.391+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:57:39.393+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:57:39.393+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:39.582+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:57:39.512+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:57:39.585+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:57:39.621+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.241 seconds
[2023-09-14T13:58:10.732+0000] {processor.py:156} INFO - Started process (PID=14365) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:10.734+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:58:10.735+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:58:10.735+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:10.833+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:58:10.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:58:10.836+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:10.883+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.156 seconds
[2023-09-14T13:58:41.112+0000] {processor.py:156} INFO - Started process (PID=14421) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:41.116+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:58:41.129+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:58:41.129+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:41.317+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:58:41.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:58:41.377+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:58:41.437+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.331 seconds
[2023-09-14T13:59:12.021+0000] {processor.py:156} INFO - Started process (PID=14478) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:12.023+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:59:12.027+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:59:12.027+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:12.823+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:59:12.302+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:59:12.936+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:13.359+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 1.342 seconds
[2023-09-14T13:59:43.791+0000] {processor.py:156} INFO - Started process (PID=14531) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:43.795+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T13:59:43.830+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:59:43.829+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:44.150+0000] {logging_mixin.py:149} INFO - [2023-09-14T13:59:44.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T13:59:44.153+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T13:59:44.194+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.407 seconds
[2023-09-14T14:00:15.073+0000] {processor.py:156} INFO - Started process (PID=14586) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:15.074+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:00:15.076+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:00:15.075+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:15.337+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:00:15.251+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:00:15.365+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:15.421+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.362 seconds
[2023-09-14T14:00:46.196+0000] {processor.py:156} INFO - Started process (PID=14644) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:46.225+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:00:46.240+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:00:46.231+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:46.791+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:00:46.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:00:46.881+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:00:47.266+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 1.134 seconds
[2023-09-14T14:01:17.568+0000] {processor.py:156} INFO - Started process (PID=14701) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:17.570+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:01:17.580+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:01:17.571+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:17.639+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:01:17.629+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:01:17.643+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:17.680+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.115 seconds
[2023-09-14T14:01:52.406+0000] {processor.py:156} INFO - Started process (PID=14757) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:52.407+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:01:52.408+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:01:52.408+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:52.472+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:01:52.457+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:01:52.475+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:01:52.541+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.139 seconds
[2023-09-14T14:02:23.791+0000] {processor.py:156} INFO - Started process (PID=14810) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:23.803+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:02:23.804+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:02:23.804+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:24.012+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:02:23.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:02:24.026+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:24.098+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.311 seconds
[2023-09-14T14:02:54.855+0000] {processor.py:156} INFO - Started process (PID=14867) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:54.857+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:02:54.858+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:02:54.858+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:54.899+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:02:54.892+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:02:54.903+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:02:54.936+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.084 seconds
[2023-09-14T14:03:25.888+0000] {processor.py:156} INFO - Started process (PID=14925) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:25.906+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:03:25.920+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:03:25.919+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:26.249+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:03:26.187+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:03:26.268+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:26.586+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.773 seconds
[2023-09-14T14:03:57.131+0000] {processor.py:156} INFO - Started process (PID=14980) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:57.149+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:03:57.156+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:03:57.155+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:57.601+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:03:57.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:03:57.613+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:03:57.648+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.564 seconds
[2023-09-14T14:04:28.027+0000] {processor.py:156} INFO - Started process (PID=15037) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:28.035+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:04:28.047+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:04:28.046+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:28.386+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:04:28.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:04:28.406+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:28.739+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.764 seconds
[2023-09-14T14:04:59.025+0000] {processor.py:156} INFO - Started process (PID=15093) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:59.036+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:04:59.038+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:04:59.037+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:59.157+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:04:59.135+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:04:59.206+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:04:59.275+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.254 seconds
[2023-09-14T14:05:29.971+0000] {processor.py:156} INFO - Started process (PID=15145) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:05:29.972+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:05:29.974+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:05:29.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:05:30.219+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:05:30.157+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:05:30.285+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:05:30.344+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.377 seconds
[2023-09-14T14:06:04.394+0000] {processor.py:156} INFO - Started process (PID=15196) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:04.395+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:06:04.406+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:06:04.406+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:04.468+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:06:04.459+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:06:04.471+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:04.532+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.142 seconds
[2023-09-14T14:06:34.881+0000] {processor.py:156} INFO - Started process (PID=15252) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:34.890+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:06:34.900+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:06:34.899+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:35.048+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:06:35.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:06:35.053+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:06:35.108+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.230 seconds
[2023-09-14T14:07:08.350+0000] {processor.py:156} INFO - Started process (PID=15302) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:08.352+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:07:08.354+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:07:08.354+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:08.529+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:07:08.504+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:07:08.535+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:08.600+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.253 seconds
[2023-09-14T14:07:38.804+0000] {processor.py:156} INFO - Started process (PID=15354) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:38.805+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:07:38.807+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:07:38.807+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:38.927+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:07:38.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:07:38.961+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:07:39.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.231 seconds
[2023-09-14T14:08:10.783+0000] {processor.py:156} INFO - Started process (PID=15408) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:10.792+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:08:10.810+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:08:10.809+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:12.894+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:08:12.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:08:12.925+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:13.449+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 2.734 seconds
[2023-09-14T14:08:45.208+0000] {processor.py:156} INFO - Started process (PID=15465) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:45.210+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:08:45.217+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:08:45.217+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:45.851+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:08:45.825+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:08:45.856+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:08:45.925+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.721 seconds
[2023-09-14T14:09:21.593+0000] {processor.py:156} INFO - Started process (PID=15526) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:21.594+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:09:21.606+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:09:21.605+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:21.647+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:09:21.637+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:09:21.650+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:21.687+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.098 seconds
[2023-09-14T14:09:52.568+0000] {processor.py:156} INFO - Started process (PID=15577) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:52.569+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:09:52.579+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:09:52.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:52.618+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:09:52.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:09:52.621+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:09:52.697+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.134 seconds
[2023-09-14T14:10:23.730+0000] {processor.py:156} INFO - Started process (PID=15633) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:23.743+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:10:23.744+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:10:23.744+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:23.801+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:10:23.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:10:23.806+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:23.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.134 seconds
[2023-09-14T14:10:54.849+0000] {processor.py:156} INFO - Started process (PID=15689) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:54.850+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:10:54.852+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:10:54.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:54.950+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:10:54.938+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:10:54.954+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:10:54.993+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.151 seconds
[2023-09-14T14:11:26.068+0000] {processor.py:156} INFO - Started process (PID=15745) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:26.077+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:11:26.079+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:11:26.079+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:26.213+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:11:26.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:11:26.218+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:26.281+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.216 seconds
[2023-09-14T14:11:56.884+0000] {processor.py:156} INFO - Started process (PID=15800) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:56.889+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:11:56.901+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:11:56.900+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:57.278+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:11:57.266+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:11:57.298+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:11:57.344+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.465 seconds
[2023-09-14T14:12:28.912+0000] {processor.py:156} INFO - Started process (PID=15857) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:12:28.919+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:12:28.935+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:12:28.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:12:29.584+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:12:29.504+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:12:29.666+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:12:30.169+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 1.313 seconds
[2023-09-14T14:13:03.015+0000] {processor.py:156} INFO - Started process (PID=15915) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:03.016+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:13:03.032+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:13:03.031+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:03.085+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:13:03.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:13:03.089+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:03.139+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.134 seconds
[2023-09-14T14:13:33.226+0000] {processor.py:156} INFO - Started process (PID=15972) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:33.227+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:13:33.228+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:13:33.228+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:33.317+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:13:33.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:13:33.322+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:13:33.405+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.184 seconds
[2023-09-14T14:14:03.906+0000] {processor.py:156} INFO - Started process (PID=16028) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:03.907+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:14:03.917+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:14:03.917+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:03.959+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:14:03.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:14:03.962+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:04.036+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.136 seconds
[2023-09-14T14:14:34.829+0000] {processor.py:156} INFO - Started process (PID=16085) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:34.830+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:14:34.840+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:14:34.832+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:34.978+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:14:34.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:14:35.020+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:14:35.109+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.285 seconds
[2023-09-14T14:15:06.355+0000] {processor.py:156} INFO - Started process (PID=16142) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:06.398+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:15:06.417+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:15:06.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:07.587+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:15:07.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:15:07.599+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:07.713+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 1.504 seconds
[2023-09-14T14:15:37.787+0000] {processor.py:156} INFO - Started process (PID=16200) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:37.794+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:15:37.814+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:15:37.812+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:37.896+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:15:37.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:15:37.901+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:15:37.958+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.174 seconds
[2023-09-14T14:16:08.185+0000] {processor.py:156} INFO - Started process (PID=16257) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:08.186+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:16:08.187+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:16:08.187+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:08.255+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:16:08.237+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:16:08.261+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:08.296+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.115 seconds
[2023-09-14T14:16:38.598+0000] {processor.py:156} INFO - Started process (PID=16314) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:38.599+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:16:38.603+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:16:38.603+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:38.674+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:16:38.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:16:38.685+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:16:38.726+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.132 seconds
[2023-09-14T14:17:08.934+0000] {processor.py:156} INFO - Started process (PID=16371) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:08.936+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:17:08.937+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:17:08.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:09.084+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:17:09.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:17:09.099+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:09.134+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.204 seconds
[2023-09-14T14:17:39.428+0000] {processor.py:156} INFO - Started process (PID=16427) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:39.432+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:17:39.434+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:17:39.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:39.479+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:17:39.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:17:39.490+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:17:39.539+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.117 seconds
[2023-09-14T14:18:10.007+0000] {processor.py:156} INFO - Started process (PID=16479) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:10.011+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:18:10.027+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:18:10.027+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:10.207+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:18:10.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:18:10.220+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:10.274+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.271 seconds
[2023-09-14T14:18:40.395+0000] {processor.py:156} INFO - Started process (PID=16536) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:40.397+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:18:40.398+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:18:40.398+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:40.527+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:18:40.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:18:40.561+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:18:40.599+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.207 seconds
[2023-09-14T14:19:11.023+0000] {processor.py:156} INFO - Started process (PID=16593) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:11.029+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:19:11.031+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:19:11.031+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:11.108+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:19:11.100+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:19:11.116+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:11.166+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.151 seconds
[2023-09-14T14:19:41.670+0000] {processor.py:156} INFO - Started process (PID=16649) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:41.672+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:19:41.673+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:19:41.673+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:41.724+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:19:41.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:19:41.728+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:19:41.770+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.112 seconds
[2023-09-14T14:20:12.355+0000] {processor.py:156} INFO - Started process (PID=16705) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:12.356+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:20:12.370+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:20:12.370+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:12.422+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:20:12.409+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:20:12.425+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:12.496+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.145 seconds
[2023-09-14T14:20:43.428+0000] {processor.py:156} INFO - Started process (PID=16762) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:43.435+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:20:43.451+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:20:43.450+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:44.189+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:20:44.017+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:20:44.319+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:20:44.709+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 1.365 seconds
[2023-09-14T14:21:15.221+0000] {processor.py:156} INFO - Started process (PID=16819) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:15.223+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:21:15.225+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:21:15.224+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:15.281+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:21:15.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:21:15.286+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:15.320+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.103 seconds
[2023-09-14T14:21:46.622+0000] {processor.py:156} INFO - Started process (PID=16872) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:46.623+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:21:46.624+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:21:46.624+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:46.683+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:21:46.676+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:21:46.686+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:21:46.756+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.139 seconds
[2023-09-14T14:22:17.117+0000] {processor.py:156} INFO - Started process (PID=16929) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:17.128+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:22:17.129+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:22:17.129+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:17.179+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:22:17.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:22:17.183+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:17.246+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.135 seconds
[2023-09-14T14:22:47.491+0000] {processor.py:156} INFO - Started process (PID=16986) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:47.504+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:22:47.506+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:22:47.506+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:47.554+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:22:47.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:22:47.557+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:22:47.611+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.133 seconds
[2023-09-14T14:23:17.754+0000] {processor.py:156} INFO - Started process (PID=17044) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:17.756+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:23:17.766+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:23:17.766+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:17.819+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:23:17.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:23:17.823+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:17.871+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.122 seconds
[2023-09-14T14:23:48.735+0000] {processor.py:156} INFO - Started process (PID=17101) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:48.736+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:23:48.738+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:23:48.738+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:48.873+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:23:48.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:23:48.877+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:23:48.946+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.216 seconds
[2023-09-14T14:24:19.192+0000] {processor.py:156} INFO - Started process (PID=17159) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:19.205+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:24:19.207+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:24:19.207+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:19.259+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:24:19.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:24:19.268+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:19.321+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.133 seconds
[2023-09-14T14:24:49.373+0000] {processor.py:156} INFO - Started process (PID=17213) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:49.375+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:24:49.376+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:24:49.376+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:49.459+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:24:49.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:24:49.463+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:24:49.512+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.143 seconds
[2023-09-14T14:25:20.471+0000] {processor.py:156} INFO - Started process (PID=17267) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:20.473+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:25:20.474+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:25:20.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:20.552+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:25:20.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:25:20.556+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:20.613+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.153 seconds
[2023-09-14T14:25:51.462+0000] {processor.py:156} INFO - Started process (PID=17322) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:51.473+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:25:51.484+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:25:51.484+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:51.572+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:25:51.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:25:51.576+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:25:51.642+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.184 seconds
[2023-09-14T14:26:22.022+0000] {processor.py:156} INFO - Started process (PID=17379) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:22.024+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:26:22.035+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:26:22.035+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:22.092+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:26:22.077+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:26:22.096+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:22.141+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.123 seconds
[2023-09-14T14:26:52.349+0000] {processor.py:156} INFO - Started process (PID=17433) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:52.350+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:26:52.351+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:26:52.351+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:52.484+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:26:52.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:26:52.488+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:26:52.547+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.201 seconds
[2023-09-14T14:27:22.920+0000] {processor.py:156} INFO - Started process (PID=17489) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:22.932+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:27:22.933+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:27:22.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:22.984+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:27:22.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:27:22.988+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:23.047+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.132 seconds
[2023-09-14T14:27:53.456+0000] {processor.py:156} INFO - Started process (PID=17545) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:53.458+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:27:53.460+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:27:53.460+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:53.523+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:27:53.506+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:27:53.532+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:27:53.582+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.149 seconds
[2023-09-14T14:28:24.167+0000] {processor.py:156} INFO - Started process (PID=17601) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:24.185+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:28:24.186+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:28:24.186+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:24.402+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:28:24.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:28:24.431+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:24.500+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.339 seconds
[2023-09-14T14:28:54.675+0000] {processor.py:156} INFO - Started process (PID=17657) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:54.677+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:28:54.678+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:28:54.678+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:54.778+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:28:54.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:28:54.781+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:28:54.817+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.146 seconds
[2023-09-14T14:29:25.217+0000] {processor.py:156} INFO - Started process (PID=17714) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:25.219+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:29:25.220+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:29:25.220+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:25.266+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:29:25.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:29:25.269+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:25.306+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.093 seconds
[2023-09-14T14:29:55.584+0000] {processor.py:156} INFO - Started process (PID=17772) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:55.601+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:29:55.610+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:29:55.610+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:55.693+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:29:55.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:29:55.698+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:29:55.741+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.161 seconds
[2023-09-14T14:30:26.217+0000] {processor.py:156} INFO - Started process (PID=17827) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:26.234+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:30:26.236+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:30:26.236+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:26.393+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:30:26.366+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:30:26.399+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:26.449+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.236 seconds
[2023-09-14T14:30:57.055+0000] {processor.py:156} INFO - Started process (PID=17884) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:57.063+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:30:57.070+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:30:57.070+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:57.240+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:30:57.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:30:57.244+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:30:57.331+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.280 seconds
[2023-09-14T14:31:28.214+0000] {processor.py:156} INFO - Started process (PID=17941) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:28.222+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:31:28.229+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:31:28.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:28.545+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:31:28.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:31:28.551+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:28.625+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.415 seconds
[2023-09-14T14:31:59.064+0000] {processor.py:156} INFO - Started process (PID=17998) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:59.087+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:31:59.088+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:31:59.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:59.154+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:31:59.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:31:59.161+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:31:59.222+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.164 seconds
[2023-09-14T14:32:29.436+0000] {processor.py:156} INFO - Started process (PID=18055) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:29.438+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:32:29.440+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:32:29.439+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:29.485+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:32:29.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:32:29.488+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:29.535+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.108 seconds
[2023-09-14T14:32:59.776+0000] {processor.py:156} INFO - Started process (PID=18112) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:59.780+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:32:59.792+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:32:59.792+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:59.840+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:32:59.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:32:59.850+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:32:59.899+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.128 seconds
[2023-09-14T14:33:30.498+0000] {processor.py:156} INFO - Started process (PID=18164) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:33:30.508+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:33:30.509+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:33:30.509+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:33:30.563+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:33:30.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:33:30.567+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:33:30.615+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.121 seconds
[2023-09-14T14:34:01.418+0000] {processor.py:156} INFO - Started process (PID=18222) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:01.420+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:34:01.432+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:34:01.431+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:01.559+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:34:01.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:34:01.565+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:01.622+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.209 seconds
[2023-09-14T14:34:32.331+0000] {processor.py:156} INFO - Started process (PID=18278) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:32.333+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:34:32.334+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:34:32.334+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:32.497+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:34:32.467+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:34:32.512+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:34:32.595+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.268 seconds
[2023-09-14T14:35:02.797+0000] {processor.py:156} INFO - Started process (PID=18334) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:02.803+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:35:02.804+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:35:02.804+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:02.857+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:35:02.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:35:02.861+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:02.904+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.111 seconds
[2023-09-14T14:35:33.182+0000] {processor.py:156} INFO - Started process (PID=18392) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:33.183+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:35:33.193+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:35:33.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:33.280+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:35:33.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:35:33.297+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:35:33.346+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.169 seconds
[2023-09-14T14:36:03.961+0000] {processor.py:156} INFO - Started process (PID=18450) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:03.962+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:36:03.964+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:36:03.963+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:04.153+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:36:04.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-14T14:36:04.156+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:04.194+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.238 seconds
[2023-09-14T14:36:32.524+0000] {processor.py:156} INFO - Started process (PID=18506) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:32.529+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:36:32.555+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:36:32.545+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:32.627+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:36:32.615+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/script/sceduler.py assumed to contain no DAGs. Skipping.
[2023-09-14T14:36:32.628+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:36:32.655+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.136 seconds
[2023-09-14T14:37:02.936+0000] {processor.py:156} INFO - Started process (PID=18562) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:02.937+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:37:02.948+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:37:02.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:02.970+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:37:02.970+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/script/sceduler.py assumed to contain no DAGs. Skipping.
[2023-09-14T14:37:02.971+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:03.010+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.079 seconds
[2023-09-14T14:37:33.328+0000] {processor.py:156} INFO - Started process (PID=18618) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:33.330+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:37:33.332+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:37:33.332+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:33.360+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:37:33.360+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/script/sceduler.py assumed to contain no DAGs. Skipping.
[2023-09-14T14:37:33.361+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:37:33.389+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.072 seconds
[2023-09-14T14:38:03.532+0000] {processor.py:156} INFO - Started process (PID=18675) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:38:03.534+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-14T14:38:03.536+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:38:03.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:38:03.569+0000] {logging_mixin.py:149} INFO - [2023-09-14T14:38:03.568+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/script/sceduler.py assumed to contain no DAGs. Skipping.
[2023-09-14T14:38:03.570+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-14T14:38:03.595+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.068 seconds
